### ISSUE TITLE
Failed all 1 attempts

### ISSUE THREAD

**Issue by onrdrsy** [gamedig/node-gamedig#146]
What could be the reason for this error? I'm pretty bad about it.
please help and thank you for this library.
```
(node:28696) UnhandledPromiseRejectionWarning: Error: Failed all 1 attempts
12:19 AM
    at QueryRunner.run (/rbd/pnpm-volume/ae1999ae-4082-4f5e-8ac6-31f44333aee1/node_modules/.registry.npmjs.org/gamedig/2.0.19/node_modules/gamedig/lib/QueryRunner.js:88:21)
12:19 AM
Attempt #1 - Port=27015 Retry=0:
12:19 AM
Error: UDP - Timed out after 2000ms
12:19 AM
    at Timeout.setTimeout (/rbd/pnpm-volume/ae1999ae-4082-4f5e-8ac6-31f44333aee1/node_modules/.registry.npmjs.org/gamedig/2.0.19/node_modules/gamedig/lib/Promises.js:7:25)
12:19 AM
    at ontimeout (timers.js:436:11)
12:19 AM
    at tryOnTimeout (timers.js:300:5)
12:19 AM
    at listOnTimeout (timers.js:263:5)
12:19 AM
    at Timer.processTimers (timers.js:223:10)
12:19 AM
(node:28696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
12:19 AM
(node:28696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by sonicsnes** [comment]
What server are you attempting to query?

**Comment by onrdrsy** [comment]
@sonicsnes 
csgo 
Default port

**Comment by sonicsnes** [comment]
What server IP? I'd need to recreate the issue that you're having.

**Comment by onrdrsy** [comment]
@sonicsnes 
Now this ip:
185.193.165.176

**Comment by sonicsnes** [comment]
It works fine for me:

```
$ bin/gamedig.js --type csgo 185.193.165.176 --debug
Q#0 Query is running with options: { socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27015,
  protocol: 'valve',
  type: 'csgo',
  host: '185.193.165.176',
  debug: true }
Q#0 DNS Lookup: 185.193.165.176
Q#0 Raw IP Address: 185.193.165.176
Q#0 Requesting info ...
Q#0 185.193.165.176:27015 UDP-->
Q#0 Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

185.193.165.176:27015 <--UDP
Buffer length: 256 bytes
ff ff ff ff 49 11 5b 54 52 5d 20 48 61 7a 65 6c 20 23 20 4a 61
            I     [  T  R  ]     H  a  z  e  l     #     J  a
69 6c 62 72 65 61 6b 20 53 75 6e 75 63 75 73 75 20 7c 20 70 72
i  l  b  r  e  a  k     S  u  n  u  c  u  s  u     |     p  r
6f 6f 79 75 6e 2e 6e 65 74 00 6a 62 5f 62 75 79 75 6b 69 73 79
o  o  y  u  n  .  n  e  t     j  b  _  b  u  y  u  k  i  s  y
61 6e 5f 73 6f 6e 5f 68 61 7a 65 6c 69 6e 00 63 73 67 6f 00 43
a  n  _  s  o  n  _  h  a  z  e  l  i  n     c  s  g  o     C
6f 75 6e 74 65 72 2d 53 74 72 69 6b 65 3a 20 47 6c 6f 62 61 6c
o  u  n  t  e  r  -  S  t  r  i  k  e  :     G  l  o  b  a  l
20 4f 66 66 65 6e 73 69 76 65 00 da 02 0a 40 00 64 6c 00 01 31
   O  f  f  e  n  s  i  v  e              @     d  l        1
2e 33 37 2e 32 2e 33 00 a1 87 69 31 32 38 74 69 63 6b 2c 61 77
.  3  7  .  2  .  3           i  1  2  8  t  i  c  k  ,  a  w
70 2c 62 75 6e 6e 79 2c 62 75 79 75 6b 69 73 79 61 6e 2c 64 65
p  ,  b  u  n  n  y  ,  b  u  y  u  k  i  s  y  a  n  ,  d  e
61 74 68 6d 61 74 63 68 2c 64 65 61 74 68 72 75 6e 2c 64 6d 2c
a  t  h  m  a  t  c  h  ,  d  e  a  t  h  r  u  n  ,  d  m  ,
68 61 7a 65 6c 2c 6a 61 69 6c 62 72 65 61 6b 2c 6a 62 2c 6d 61
h  a  z  e  l  ,  j  a  i  l  b  r  e  a  k  ,  j  b  ,  m  a
72 6b 65 74 2c 6d 67 2c 70 72 6f 6f 79 75 6e 2c 73 75 72 66 2c
r  k  e  t  ,  m  g  ,  p  r  o  o  y  u  n  ,  s  u  r  f  ,
74 72 2c 74 75 72 6b 65 79 2c 73 65 63 75 72 65 00 da 02 00 00
t  r  ,  t  u  r  k  e  y  ,  s  e  c  u  r  e
00 00 00 00


Q#0 Registered RTT: 194ms
Q#0 Received full packet
Q#0 Received 49 expected 49
Q#0 UDP send finished by callback
Q#0 STEAM APPID: 730
Q#0 PROTOCOL: 17
Q#0 Requesting player list ...
Q#0 185.193.165.176:27015 UDP-->
Q#0 Buffer length: 9 bytes
ff ff ff ff 55 ff ff ff ff
            U

185.193.165.176:27015 <--UDP
Buffer length: 9 bytes
ff ff ff ff 41 99 ea 94 0b
            A

Q#0 Registered RTT: 191ms
Q#0 Received full packet
Q#0 Received 41 expected 44
Q#0 Received new challenge key: 194308761
Q#0 Challenge key changed -- allowing query retry if needed
Q#0 UDP send finished by callback
Q#0 185.193.165.176:27015 UDP-->
Q#0 Buffer length: 9 bytes
ff ff ff ff 55 99 ea 94 0b
            U

185.193.165.176:27015 <--UDP
Buffer length: 195 bytes
ff ff ff ff 44 0a 00 e3 83 84 20 45 6d 62 72 75 6a 6f 6d 20 20
            D                    E  m  b  r  u  j  o  m
e3 83 84 00 00 00 00 00 d8 7b 8e 45 00 45 67 65 6d 65 6e 20 e8
                           {     E     E  g  e  m  e  n
a3 81 e6 b1 ba 00 08 00 00 00 00 03 25 45 00 4d 63 52 49 5a 41
                                    %  E     M  c  R  I  Z  A
00 13 00 00 00 00 9d d1 44 00 c2 bf 77 e1 b4 80 c9 b4 e1 b4 85
                        D           w
ca 8f 00 02 00 00 00 00 49 cc 44 00 50 72 6f 77 6e 00 05 00 00
                        I     D     P  r  o  w  n
00 7f e6 a4 44 00 46 69 61 72 75 6b 41 62 69 00 06 00 00 00 ff
            D     F  i  a  r  u  k  A  b  i
bd f7 43 00 74 72 6b 4e 4e 4e 21 20 63 73 00 06 00 00 00 fd 07
      C     t  r  k  N  N  N  !     c  s
df 43 00 4d 59 4e 6f 6f 6e 00 01 00 00 00 fe 6f db 43 00 50 61
   C     M  Y  N  o  o  n                    o     C     P  a
62 6c 6f 00 00 00 00 00 fa eb 1b 43 00 6c 6f 52 45 45 00 00 00
b  l  o                          C     l  o  R  E  E
00 00 f1 67 90 42
         g     B

Q#0 Registered RTT: 203ms
Q#0 Received full packet
Q#0 Received 44 expected 44
Q#0 UDP send finished by callback
Q#0 Found player: ツ Embrujom  ツ 0 4559.48046875
Q#0 Found player: Egemen 裁決 8 2640.1875
Q#0 Found player: McRIZA 19 1676.90625
Q#0 Found player: ¿wᴀɴᴅʏ 2 1634.28125
Q#0 Found player: Prown 5 1319.2030029296875
Q#0 Found player: FiarukAbi 6 495.4843444824219
Q#0 Found player: trkNNN! cs 6 446.0624084472656
Q#0 Found player: MYNoon 1 438.87493896484375
Q#0 Found player: Pablo 0 155.92178344726562
Q#0 Found player: loREE 0 72.20301055908203
Q#0 Requesting rules ...
Q#0 185.193.165.176:27015 UDP-->
Q#0 Buffer length: 9 bytes
ff ff ff ff 56 99 ea 94 0b
            V

Q#0 UDP timeout detected
Q#0 UDP timeout resolved by callback
Q#0 Size of players array: 10
Q#0 Size of bots array: 0
Q#0 Query was successful
{
  "name": "[TR] Hazel # Jailbreak Sunucusu | prooyun.net",
  "map": "jb_buyukisyan_son_hazelin",
  "password": false,
  "raw": {
    "protocol": 17,
    "folder": "csgo",
    "game": "Counter-Strike: Global Offensive",
    "steamappid": 730,
    "numplayers": 10,
    "numbots": 0,
    "listentype": "d",
    "environment": "l",
    "secure": 1,
    "version": "1.37.2.3",
    "tags": "128tick,awp,bunny,buyukisyan,deathmatch,deathrun,dm,hazel,jailbreak,jb,market,mg,prooyun,surf,tr,turkey,secure",
    "gameid": "730",
    "rules": {}
  },
  "maxplayers": 64,
  "players": [
    {
      "name": "ツ Embrujom  ツ",
      "score": 0,
      "time": 4559.48046875
    },
    {
      "name": "Egemen 裁決",
      "score": 8,
      "time": 2640.1875
    },
    {
      "name": "McRIZA",
      "score": 19,
      "time": 1676.90625
    },
    {
      "name": "¿wᴀɴᴅʏ",
      "score": 2,
      "time": 1634.28125
    },
    {
      "name": "Prown",
      "score": 5,
      "time": 1319.2030029296875
    },
    {
      "name": "FiarukAbi",
      "score": 6,
      "time": 495.4843444824219
    },
    {
      "name": "trkNNN! cs",
      "score": 6,
      "time": 446.0624084472656
    },
    {
      "name": "MYNoon",
      "score": 1,
      "time": 438.87493896484375
    },
    {
      "name": "Pablo",
      "score": 0,
      "time": 155.92178344726562
    },
    {
      "name": "loREE",
      "score": 0,
      "time": 72.20301055908203
    }
  ],
  "bots": [],
  "connect": "185.193.165.176:27015",
  "ping": 191
}
```

If running the query with `debug: true` immediately returns a udp timeout for you, it's likely an issue with your firewall or ISP preventing the query pings from being sent.

**Comment by onrdrsy** [comment]
@sonicsnes 
the query is running if I use the old version(1.0.49) of gamedig.

**Comment by sonicsnes** [comment]
@onrdrsy That's very strange. What is the newer version you are using? What is the output if you enable debug?

**Comment by onrdrsy** [comment]
@sonicsnes 
currently 2.0.19
Debug same my first message.  Thanks for reply.

**Comment by sonicsnes** [comment]
In debug mode, additional debug lines are printed to the output, beginning with `Query is running with options`. Can you post them?

**Comment by LightLewis** [comment]
Sorry to bump this but in your options for the latest version user `host: ip` instead of `ip: ip`

**Comment by onrdrsy** [comment]
> Sorry to bump this but in your options for the latest version user `host: ip` instead of `ip: ip`

unfortunately the result is the same. thank you for reply.

**Comment by xCausxn** [comment]
@onrdrsy 
Running on version 2.0.20

`node .\bin\gamedig.js --type csgo --host 185.193.165.176 --port 27015`

Response
```
{"name":"[TR] Hazel # Jailbreak Sunucusu | prooyun.net","map":"jb_buyukisyan_son-hazel","password":false,"raw":{"protocol":17,"folder":"csgo","game":"Counter-Strike: Global Offensive","steamappid":730,"numplayers":50,"numbots":0,"listentype":"d","environment":"l","secure":1,"version":"1.37.2.3","tags":"128tick,awp,bunny,buyukisyan,deathmatch,deathrun,dm,hazel,jailbreak,jb,market,mg,prooyun,surf,tr,turkey,secure","gameid":"730","rules":{}},"maxplayers":64,"players":[{"name":"save me","score":40,"time":10104.7470703125},{"name":"Pala Remzi.exe","score":0,"time":10081.84765625},{"name":"Kirika #GGKA","score":60,"time":10081.72265625},{"name":"G-Avatar","score":0,"time":10081.64453125},{"name":"sessizkmdn","score":2,"time":10081.55078125},{"name":"EgoEgo","score":35,"time":10081.48828125},{"name":"CptKagan","score":9,"time":10081.45703125},{"name":"TURKISH DELIGHT","score":30,"time":10081.4560546875},{"name":"ClosY","score":0,"time":10081.4560546875},{"name":"ツ Embrujom  ツ","score":0,"time":10081.2783203125},{"name":"Shânks™","score":74,"time":10080.98046875},{"name":"¿héss","score":4,"time":10080.71484375},{"name":"Lorex","score":0,"time":10076.265625},{"name":"Raunos. 185.193.165.176","score":58,"time":10075.8583984375},{"name":"`K? sc | SeeCanMeWar*","score":57,"time":10075.638671875},{"name":"Whentanne 185.193.165.176","score":3,"time":10067.9501953125},{"name":"KreEZZ","score":2,"time":8898.962890625},{"name":"cruel","score":0,"time":8112.19140625},{"name":"Arda Pasha185.193.165.176","score":7,"time":7315.939453125},{"name":"YeedBossykT","score":9,"time":4444.1142578125},{"name":"10balkes10","score":0,"time":3933.63818359375},{"name":"AlliE","score":6,"time":3910.0771484375},{"name":"Cactus Jack","score":9,"time":3313.864013671875},{"name":"Tek_7_Hack_Dedi","score":21,"time":2984.279296875},{"name":"Tommy_Eweninq","score":3,"time":2865.138671875},{"name":"Mr. Lawyer","score":5,"time":2863.607177734375},{"name":"MYNoon™","score":16,"time":2605.520751953125},{"name":"☾★NE MUTLU TÜRKÜM DİYENE☾★","score":25,"time":2591.496826171875},{"name":"Mehendizz","score":0,"time":2173.682373046875},{"name":"Bloodey","score":0,"time":2145.744873046875},{"name":"♕Younes♕","score":32,"time":2060.791748046875},{"name":"BEVAT","score":20,"time":2018.4166259765625},{"name":"yusuferdogan2005","score":0,"time":1800.5118408203125},{"name":"Kai ✪","score":25,"time":1791.8709716796875},{"name":"Aspect","score":0,"time":1692.33984375},{"name":"Blacefine","score":10,"time":1653.886962890625},{"name":"BOZAN'21`","score":0,"time":1347.386474609375},{"name":"Qluady.Exe","score":0,"time":727.7799072265625},{"name":"Wâcey","score":5,"time":703.42041015625},{"name":"SarıCan","score":6,"time":620.8268432617188},{"name":"「 XLOREAX 」","score":32,"time":568.3890991210938},{"name":"KlenX","score":1,"time":538.37353515625},{"name":"Ayı Kardeş","score":6,"time":515.4667358398438},{"name":"¿wâncé","score":0,"time":498.1546325683594},{"name":"GDE/LimonluPoaça","score":0,"time":335.5585632324219},{"name":"BenAceSyber","score":0,"time":213.39056396484375},{"name":"ツ Bloo ツ","score":0,"time":93.70296478271484},{},{},{}],"bots":[],"connect":"185.193.165.176:27015","ping":59}
```

Are you running it from the command line or using it as a library?
Are you receiving the error during local development or when running on a server?

I suspect there is something going on with the networking.

**Comment by ZixeSea** [comment]
Get the same thing everything returns an error except normal minecraft.
Everything returns Server is offline (Error: Failed all 1 attempts) and pinging works fine.

Some IP/games I tried for example:
spaceengineers 46.4.244.164:27017
spaceengineers s1.rebels-games.com:27016
spaceengineers 93.99.7.33:29016
spaceengineers fgcse.ddns.net:27016
spaceengineers 89.163.212.94:27016
spaceengineers coreserversau.com:27016
csgo 216.52.148.47:27015
csgo 188.212.100.42:27015
minecraftbe play.drpe.net:19132
minecraftbe play.fallentech.io:19132
minecraftbe play.primegames.net:19132
minecraftbe Play.SkyBlockpe.com:19132

**Comment by mmorrisontx** [comment]
Closing since we've made tons of improvements to the csgo protocol since this issue was opened. If you still experience problems, please open a new issue.
