### ISSUE TITLE
Unable to query Starbound

### ISSUE THREAD

**Issue by HVEVB** [gamedig/node-gamedig#186]
Hey!
I'm trying to query a Starbound server but gamedig can't connect to it for some reason. I enabled the debug option, and here's the output
```
Q#0 Query is running with options: {
  socketTimeout: 5000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 21025,
  protocol: 'valve',
  type: 'starbound',
  host: '92.244.223.170',
  debug: true
}
Q#0 DNS Lookup: 92.244.223.170
Q#0 Raw IP Address: 92.244.223.170
Q#0 Requesting info ...
Q#0 92.244.223.170:21025 UDP-->
Q#0 Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

92.244.223.170:21025 <--UDP
Buffer length: 71 bytes
ff ff ff ff 49 07 41 20 53 74 61 72 62 6f 75 6e 64 20 53 65 72
            I     A     S  t  a  r  b  o  u  n  d     S  e  r
76 65 72 00 55 6e 6b 6e 6f 77 6e 00 73 74 61 72 62 6f 75 6e 64
v  e  r     U  n  k  n  o  w  n     s  t  a  r  b  o  u  n  d
00 53 74 61 72 62 6f 75 6e 64 00 fe ff 00 45 00 44 57 00 00 31
   S  t  a  r  b  o  u  n  d              E     D  W        1
2e 34 2e 34 00 80 00 00
.  4  .  4

Q#0 Registered RTT: 7ms
Q#0 Received full packet
Q#0 Received 49 expected 49
Q#0 UDP send finished by callback
Q#0 STEAM APPID: 65534
Q#0 PROTOCOL: 7
Q#0 Requesting player list ...
Q#0 92.244.223.170:21025 UDP-->
Q#0 Buffer length: 9 bytes
ff ff ff ff 55 ff ff ff ff
            U

192.168.1.3:21025 <--UDP
Buffer length: 9 bytes
ff ff ff ff 41 36 1b 4c b9
            A  6     L

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 5000ms
    at Timeout.<anonymous> (C:\xampp\htdocs\Dojnaz\API\node_modules\gamedig\lib\Promises.js:7:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: Failed all 1 attempts
    at QueryRunner.run (C:\xampp\htdocs\Dojnaz\API\node_modules\gamedig\lib\QueryRunner.js:88:21)
Attempt #1 - Port=21025 Retry=0:
Error: UDP - Timed out after 5000ms
    at Timeout.<anonymous> (C:\xampp\htdocs\Dojnaz\API\node_modules\gamedig\lib\Promises.js:7:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
And the server has this config
```
  "queryServerBind" : "*",
  "queryServerPort" : 21025,
  "runQueryServer" : true,
```

**Comment by mmorrisontx** [comment]
Closing since I think we fixed this issue in an unrelated ticket at some point (player response on valve protocol is now optional because csgo likes to not respond to it as well).
