### ISSUE TITLE
Conan Exiles server queries throwing UDP errors

### ISSUE THREAD

**Issue by passivedragon** [gamedig/node-gamedig#193]
I've tried this with various methods now, commandline, in script, both on local PC and on repl.it, with various servers and port variations.

No matter what I do or try, even after correcting the query port set in the games.txt according to https://www.conanexiles.com/dedicated-servers/ and testing that with servers I know the query port with, I can't seem to get this to work.

https://repl.it/@passivedragon/gamedig-testing this is what I've tried, also locally.
Results:
```
{
  "name": "gamedig-testing",
Q#0 Query is running with options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27015,
  protocol: 'valve',
  type: 'conanexiles',
  host: '172.107.169.170',
  debug: true
}
Q#0 DNS Lookup: 172.107.169.170
Q#0 Raw IP Address: 172.107.169.170
Promise { <pending> }
Q#0 Requesting info ...
Q#0 172.107.169.170:27015 UDP-->
Q#0 Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75 
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u  
65 72 79 00 
e  r  y     

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/home/runner/gamedig-testing/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
didn't work Error: Failed all 1 attempts
    at QueryRunner.run (/home/runner/gamedig-testing/node_modules/gamedig/lib/QueryRunner.js:88:21)
Attempt #1 - Port=27015 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/home/runner/gamedig-testing/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)```

And from console:

![cmd_R3HgtqUexs](https://user-images.githubusercontent.com/54485880/91913622-5acfeb00-ecb6-11ea-973c-014f611183b6.png)

If this is purely a firewall type issue, what local ports would have to be accessible? I've spent too much time on this to still keep an overview.

**Comment by mmorrisontx** [comment]
Conan exiles uses an arbitrary query port. By default, it's 27015, but on shared hosts, it can be whatever they set it to. For the IP you listed, I happened to (just by chance by googling) find that there's a server running on game port 28120 and query port 28122: https://www.battlemetrics.com/servers/conanexiles/8101891

Running `gamedig --type conanexiles 172.107.169.170:28122 --debug` gets us a bit further, and successfully retrieves the global info but not the player list:
```
Q#0 Query is running with options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 28122,
  protocol: 'valve',
  type: 'conanexiles',
  host: '172.107.169.170',
  debug: true
}
Q#0 DNS Lookup: 172.107.169.170
Q#0 Raw IP Address: 172.107.169.170
Q#0 Requesting info ...
Q#0 172.107.169.170:28122 UDP-->
Q#0 Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

172.107.169.170:28122 <--UDP
Buffer length: 58 bytes
ff ff ff ff 49 02 45 6d 65 72 69 61 6c 20 52 50 00 54 68 65 20
            I     E  m  e  r  i  a  l     R  P     T  h  e
45 78 69 6c 65 64 20 4c 61 6e 64 73 00 00 43 6f 6e 61 6e 20 45
E  x  i  l  e  d     L  a  n  d  s        C  o  n  a  n     E
78 69 6c 65 73 00 00 00 1b 28 00 64 77 00 01 00
x  i  l  e  s              (     d  w

Q#0 Registered RTT: 42ms
Q#0 Received full packet
Q#0 Received 49 expected 49
Q#0 UDP send finished by callback
Q#0 STEAM APPID: 0
Q#0 PROTOCOL: 2
Q#0 Requesting player list ...
Q#0 172.107.169.170:28122 UDP-->
Q#0 Buffer length: 9 bytes
ff ff ff ff 55 ff ff ff ff
            U

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
```

It's possible that conanexiles doesn't support serving the player list, and we should just skip that step for this protocol...

**Comment by mmorrisontx** [comment]
Fixed that issue in 81a3ec10193fd3f5752689a226c51d8d29dbab25. Give 2.0.23 a shot, but beware that you'll still need to have the proper query port for the game -- it's not always 27015.

`gamedig --type conanexiles 172.107.169.170:28122` now gives me:
```
{"name":"Emerial RP","map":"The Exiled Lands","password":false,"raw":{"protocol"
:2,"folder":"","game":"Conan Exiles","steamappid":0,"numplayers":29,"numbots":0,
"listentype":"d","environment":"w","secure":1,"version":"","rules":{}},"maxplaye
rs":40,"players":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}
,{},{},{},{},{},{},{},{}],"bots":[],"connect":"172.107.169.170:28122","ping":39}
```

**Comment by passivedragon** [comment]
Thank you

**Comment by passivedragon** [comment]
Personally I can't seem to get the response that you've showed there.
Trying that via command line results in the same things as before for me, just like the library version.
[https://repl.it/@passivedragon/gamedig-testing](https://repl.it/@passivedragon/gamedig-testing)
It's clearly updated to 2.023 but I can't see any change.

**Comment by mmorrisontx** [comment]
repl.it is almost certainly running scripts in a sandbox which doesn't allow incoming udp. Typically, only tcp protocols can navigate the firewall of isolation sandboxes such as those.
