### ISSUE TITLE
CS:GO Server Timeout Problem

### ISSUE THREAD

**Issue by MissXecutioner** [gamedig/node-gamedig#201]
```
Q#0 Query is running with options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27015,
  protocol: 'valve',
  type: 'csgo',
  host: '185.198.75.5',
  debug: true
}
Q#0 DNS Lookup: 185.198.75.5
Q#0 Raw IP Address: 185.198.75.5
Q#0 Requesting info ...
Q#0 185.198.75.5:27015 UDP-->
Q#0 Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/usr/lib/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Error: Failed all 1 attempts
    at QueryRunner.run (/usr/lib/node_modules/gamedig/lib/QueryRunner.js:88:21)
Attempt #1 - Port=27015 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/usr/lib/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

I will try to get a player name, but the query connection is not established. I get an error in this way. IP address is correct. Is there any help?

**Comment by mmorrisontx** [comment]
It works properly for me locally, which means that the internet connection or machine you are running the query from is likely blocking incoming UDP packets from the remote server. Alternatively, the remote server may have blocked your IP if you are running the query from a shared host.

```
bin/gamedig.js --type csgo 185.198.75.5 --debug
Q#0 Query is running with options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27015,
  protocol: 'valve',
  type: 'csgo',
  host: '185.198.75.5',
  debug: true
}
Q#0 DNS Lookup: 185.198.75.5
Q#0 Raw IP Address: 185.198.75.5
Q#0 Requesting info ...
Q#0 185.198.75.5:27015 UDP-->
Q#0 Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

185.198.75.5:27015 <--UDP
Buffer length: 299 bytes
ff ff ff ff 49 11 5b 54 52 5d 20 49 4d 50 41 52 41 54 4f 52 20
            I     [  T  R  ]     I  M  P  A  R  A  T  O  R
47 41 4d 49 4e 47 20 4a 41 49 4c 42 52 45 41 4b 20 45 46 53 41
G  A  M  I  N  G     J  A  I  L  B  R  E  A  K     E  F  S  A
4e 45 53 c4 b0 20 23 32 30 31 33 20 7c 20 6f 79 75 6e 68 6f 73
N  E  S           #  2  0  1  3     |     o  y  u  n  h  o  s
74 2e 6e 65 74 00 6a 62 5f 62 75 79 75 6b 69 73 79 61 6e 5f 73
t  .  n  e  t     j  b  _  b  u  y  u  k  i  s  y  a  n  _  s
6f 6e 5f 69 6d 70 61 72 61 74 6f 72 00 63 73 67 6f 00 43 6f 75
o  n  _  i  m  p  a  r  a  t  o  r     c  s  g  o     C  o  u
6e 74 65 72 2d 53 74 72 69 6b 65 3a 20 47 6c 6f 62 61 6c 20 4f
n  t  e  r  -  S  t  r  i  k  e  :     G  l  o  b  a  l     O
66 66 65 6e 73 69 76 65 00 da 02 0e 28 00 64 6c 00 01 31 2e 33
f  f  e  n  s  i  v  e              (     d  l        1  .  3
37 2e 37 2e 30 00 a1 87 69 21 20 6f 79 75 6e 68 6f 73 74 2e 6e
7  .  7  .  0           i  !     o  y  u  n  h  o  s  t  .  n
65 74 20 21 2c 33 2d 35 2c 61 69 6d 2c 61 77 70 2c 62 75 79 75
e  t     !  ,  3  -  5  ,  a  i  m  ,  a  w  p  ,  b  u  y  u
6b 69 73 79 61 6e 2c 64 65 61 74 68 72 75 6e 2c 64 72 2c 66 75
k  i  s  y  a  n  ,  d  e  a  t  h  r  u  n  ,  d  r  ,  f  u
6e 2c 69 73 79 61 6e 2c 6a 61 69 6c 2c 6a 61 69 6c 62 72 65 61
n  ,  i  s  y  a  n  ,  j  a  i  l  ,  j  a  i  l  b  r  e  a
6b 2c 6a 62 2c 6b 6f 72 75 6d 61 2c 6c 65 2c 6d 67 2c 6f 62 61
k  ,  j  b  ,  k  o  r  u  m  a  ,  l  e  ,  m  g  ,  o  b  a
6d 61 2c 6f 79 75 6e 68 61 76 75 7a 75 2c 70 61 72 74 79 2c 70
m  a  ,  o  y  u  n  h  a  v  u  z  u  ,  p  a  r  t  y  ,  p
67 67 2c 72 65 64 6c 69 6e 65 2c 73 65 63 75 72 65 00 da 02 00
g  g  ,  r  e  d  l  i  n  e  ,  s  e  c  u  r  e
00 00 00 00 00


Q#0 Registered RTT: 210ms
Q#0 Received full packet
Q#0 Received 49 expected 49
Q#0 UDP send finished by callback
Q#0 INFO:  {
  protocol: 17,
  folder: 'csgo',
  game: 'Counter-Strike: Global Offensive',
  steamappid: 730,
  numplayers: 14,
  numbots: 0,
  listentype: 'd',
  environment: 'l',
  secure: 1,
  version: '1.37.7.0',
  tags: '! oyunhost.net !,3-5,aim,awp,buyukisyan,deathrun,dr,fun,isyan,jail,jail
break,jb,koruma,le,mg,obama,oyunhavuzu,party,pgg,redline,secure',
  gameid: '730'
}
Q#0 Requesting player list ...
Q#0 185.198.75.5:27015 UDP-->
Q#0 Buffer length: 9 bytes
ff ff ff ff 55 ff ff ff ff
            U

185.198.75.5:27015 <--UDP
Buffer length: 9 bytes
ff ff ff ff 41 92 5c 1b 06
            A     \

Q#0 Registered RTT: 210ms
Q#0 Received full packet
Q#0 Received 41 expected 44
Q#0 Received new challenge key: 102456466
Q#0 Challenge key changed -- allowing query retry if needed
Q#0 UDP send finished by callback
Q#0 185.198.75.5:27015 UDP-->
Q#0 Buffer length: 9 bytes
ff ff ff ff 55 92 5c 1b 06
            U     \

185.198.75.5:27015 <--UDP
Buffer length: 357 bytes
ff ff ff ff 44 0f 00 47 6f 6c 44 41 52 4b 00 5a 00 00 00 5f 25
            D        G  o  l  D  A  R  K     Z           _  %
02 46 00 48 61 73 61 6e 20 31 38 35 2e 31 39 38 2e 37 35 2e 35
   F     H  a  s  a  n     1  8  5  .  1  9  8  .  7  5  .  5
00 00 00 00 00 88 81 a8 45 00 53 75 70 72 65 6d 65 20 20 31 38
                        E     S  u  p  r  e  m  e        1  8
35 2e 31 39 38 2e 37 35 2e 35 00 05 00 00 00 4a b7 a7 45 00 e2
5  .  1  9  8  .  7  5  .  5                 J        E
8c 9c 42 6f 6f 6d e2 8c 9f 20 42 65 73 74 20 6f 66 20 4d 69 6c
      B  o  o  m              B  e  s  t     o  f     M  i  l
6b 00 26 00 00 00 4a 32 96 45 00 52 45 44 55 58 00 04 00 00 00
k     &           J  2     E     R  E  D  U  X
ea 80 95 45 00 62 6f 75 6e 63 65 72 20 31 38 35 2e 31 39 38 2e
         E     b  o  u  n  c  e  r     1  8  5  .  1  9  8  .
37 35 2e 35 00 06 00 00 00 cb cb 84 45 00 4b c4 b0 4e 47 00 13
7  5  .  5                          E     K        N  G
00 00 00 17 cb 7f 45 00 53 6c 61 72 65 58 00 0a 00 00 00 56 4c
                  E     S  l  a  r  e  X                 V  L
53 45 00 42 6f 62 62 79 20 53 68 6d 75 72 64 61 20 47 2e 53 2e
S  E     B  o  b  b  y     S  h  m  u  r  d  a     G  .  S  .
39 00 0f 00 00 00 23 44 68 44 00 44 52 c4 b0 56 45 42 59 5f 33
9                 #  D  h  D     D  R        V  E  B  Y  _  3
35 5f 41 52 44 41 00 07 00 00 00 b6 e1 19 44 00 53 65 4f 64 65
5  _  A  R  D  A                          D     S  e  O  d  e
58 20 62 75 74 20 53 41 44 00 00 00 00 00 bb 9e 18 44 00 7c 20
X     b  u  t     S  A  D                          D     |
e2 98 ac e0 b9 96 db a3 db 9c c7 a4 68 6f 73 74 e0 bc bb 20 7c
                                    h  o  s  t              |
00 00 00 00 00 46 67 c7 43 00 7a 78 79 6e 41 2d 00 00 00 00 00
               F  g     C     z  x  y  n  A  -
91 12 7a 43 00 42 4c 41 43 4b 4a 41 43 4b 48 33 35 00 00 00 00
      z  C     B  L  A  C  K  J  A  C  K  H  3  5
00 91 fa 73 43 00 4f 78 79 47 65 6e 00 00 00 00 00 8d 5e 73 43
         s  C     O  x  y  G  e  n                    ^  s  C

Q#0 Registered RTT: 194ms
Q#0 Received full packet
Q#0 Received 44 expected 44
Q#0 UDP send finished by callback
Q#0 Found player: GolDARK 90 8329.3427734375
Q#0 Found player: Hasan 185.198.75.5 0 5392.19140625
Q#0 Found player: Supreme  185.198.75.5 5 5366.9111328125
Q#0 Found player: ⌜Boom⌟ Best of Milk 38 4806.2861328125
Q#0 Found player: REDUX 4 4784.1142578125
Q#0 Found player: bouncer 185.198.75.5 6 4249.47412109375
Q#0 Found player: KİNG 19 4092.693115234375
Q#0 Found player: SlareX 10 3380.77099609375
Q#0 Found player: Bobby Shmurda G.S.9 15 929.0646362304688
Q#0 Found player: DRİVEBY_35_ARDA 7 615.5267333984375
Q#0 Found player: SeOdeX but SAD 0 610.4801635742188
Q#0 Found player: | ☬๖ۣۜǤhost༻ | 0 398.80682373046875
Q#0 Found player: zxynA- 0 250.07252502441406
Q#0 Found player: BLACKJACKH35 0 243.97877502441406
Q#0 Found player: OxyGen 0 243.3693389892578
Q#0 Requesting rules ...
Q#0 185.198.75.5:27015 UDP-->
Q#0 Buffer length: 9 bytes
ff ff ff ff 56 92 5c 1b 06
            V     \

Q#0 UDP timeout detected
Q#0 UDP timeout resolved by callback
Q#0 Size of players array: 15
Q#0 Size of bots array: 0
Q#0 Query was successful
{
  "name": "[TR] IMPARATOR GAMING JAILBREAK EFSANESİ #2013 | oyunhost.net",
  "map": "jb_buyukisyan_son_imparator",
  "password": false,
  "raw": {
    "protocol": 17,
    "folder": "csgo",
    "game": "Counter-Strike: Global Offensive",
    "steamappid": 730,
    "numplayers": 14,
    "numbots": 0,
    "listentype": "d",
    "environment": "l",
    "secure": 1,
    "version": "1.37.7.0",
    "tags": "! oyunhost.net !,3-5,aim,awp,buyukisyan,deathrun,dr,fun,isyan,jail,
jailbreak,jb,koruma,le,mg,obama,oyunhavuzu,party,pgg,redline,secure",
    "gameid": "730",
    "rules": {}
  },
  "maxplayers": 40,
  "players": [
    {
      "name": "GolDARK",
      "score": 90,
      "time": 8329.3427734375
    },
    {
      "name": "Hasan 185.198.75.5",
      "score": 0,
      "time": 5392.19140625
    },
    {
      "name": "Supreme  185.198.75.5",
      "score": 5,
      "time": 5366.9111328125
    },
    {
      "name": "⌜Boom⌟ Best of Milk",
      "score": 38,
      "time": 4806.2861328125
    },
    {
      "name": "REDUX",
      "score": 4,
      "time": 4784.1142578125
    },
    {
      "name": "bouncer 185.198.75.5",
      "score": 6,
      "time": 4249.47412109375
    },
    {
      "name": "KİNG",
      "score": 19,
      "time": 4092.693115234375
    },
    {
      "name": "SlareX",
      "score": 10,
      "time": 3380.77099609375
    },
    {
      "name": "Bobby Shmurda G.S.9",
      "score": 15,
      "time": 929.0646362304688
    },
    {
      "name": "DRİVEBY_35_ARDA",
      "score": 7,
      "time": 615.5267333984375
    },
    {
      "name": "SeOdeX but SAD",
      "score": 0,
      "time": 610.4801635742188
    },
    {
      "name": "| ☬๖ۣۜǤhost༻ |",
      "score": 0,
      "time": 398.80682373046875
    },
    {
      "name": "zxynA-",
      "score": 0,
      "time": 250.07252502441406
    },
    {
      "name": "BLACKJACKH35",
      "score": 0,
      "time": 243.97877502441406
    },
    {
      "name": "OxyGen",
      "score": 0,
      "time": 243.3693389892578
    }
  ],
  "bots": [],
  "connect": "185.198.75.5:27015",
  "ping": 194
}
```

**Comment by MissXecutioner** [comment]
When I took my vds location to the European location, it was improved thanks.
