### ISSUE TITLE
Failed all 1 attempts for garrys mod server

### ISSUE THREAD

**Issue by PikPakPik** [gamedig/node-gamedig#279]
Hello i have encountered a error when i want to use gamedig, i use the command for test with --debug i have this

```
root@Vpstahlewandowski:~# gamedig --type garrysmod 193.70.80.207:27015 --debug
Q#0 Starting
Q#0 Protocol: Valve
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27015,
  protocol: 'valve',
  requestRules: false,
  type: 'garrysmod',
  host: '193.70.80.207',
  debug: true
}
Q#0 DNS Lookup: 193.70.80.207
Q#0 Raw IP Address: 193.70.80.207
Q#0 Requesting info ...
193.70.80.207:27015 UDP(55112)-->
Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

193.70.80.207:27015 <--UDP(55112)
Buffer length: 9 bytes
ff ff ff ff 41 66 09 75 27
            A  f     u  '

Q#0 Registered RTT: 50ms
Q#0 Received full packet
Q#0 Received 0x41 expected 0x49
Q#0 Received new challenge key: 0x27750966
Q#0 UDP send finished by callback
193.70.80.207:27015 UDP(55112)-->
Buffer length: 29 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00 66 09 75 27
e  r  y     f     u  '

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/root/.nvm/versions/node/v16.9.1/lib/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error: Failed all 1 attempts
    at QueryRunner.run (/root/.nvm/versions/node/v16.9.1/lib/node_modules/gamedig/lib/QueryRunner.js:95:21)
    at async Gamedig.query (/root/.nvm/versions/node/v16.9.1/lib/node_modules/gamedig/lib/index.js:11:16)
Attempt #1 - Port=27015 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/root/.nvm/versions/node/v16.9.1/lib/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)```

Can you help me please

**Comment by Whitee303** [comment]
The same in Multi Theft Auto

``Error: Failed all 2 attempts
    at QueryRunner.run (C:\Users\\Downloads\Richpresence\node_modules\gamedig\lib\QueryRunner.js:95:21)
    at async Gamedig.query (C:\Users\\Downloads\Richpresence\node_modules\gamedig\lib\index.js:11:16)
    at async Function.query (C:\Users\\Downloads\Richpresence\node_modules\gamedig\lib\index.js:19:16)
Attempt #1 - Port=22126 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (C:\Users\\Downloads\Richpresence\node_modules\gamedig\lib\Promises.js:7:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Attempt #2 - Port=22003 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (C:\Users\\Downloads\Richpresence\node_modules\gamedig\lib\Promises.js:7:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)``

**Comment by bellum128** [comment]
I am also encountering this issue with Garry's Mod.

**Comment by merisanualex** [comment]
I have the same issue with CS1.6 only when trying the request from AWS, from my PC it works

**Comment by bellum128** [comment]
Just did some tests on other machines which actually worked, then I realized the global version I was using via NVM path was using the system version for some reason which was still on release @2.x, not the @4.x I had set it to for the node version I had selection.

All in all, I am not getting the error when doing adhoc gamedig queries anymore after putting it on @4.x, however it is not properly getting the full player list at times in my actual web application I am building, which is on the latest version for its project. I will continue troubleshooting a bit for that one, and may open a separate issue if I still encounter this issue.

**Comment by Yaguxxx** [comment]
no support ?

**Comment by bellum128** [comment]
Did you make extra sure you're on the latest version? Again I had thought I was, but upon actually running ```whereis gamedig``` and checking the NPM library in that location, I had realized NVM wasn't using the correct one and such...so I would just make extra sure that what you're looking at is the 4.x branch.

**Comment by CosminPerRam** [comment]
Quite an old issue, but this seems just to be a networking issue, try increasing the `socketTimeout` option and make sure you're on the latest version (like @bellum128 said), if you still do encounter issues, feel free to re open this.
