### ISSUE TITLE
SvelteKit website crashing when deployed to Vercel

### ISSUE THREAD

**Issue by maxijabase** [gamedig/node-gamedig#309]
My website (https://github.com/electricservers/electricservers.com.ar) deployed in https://electricservers.com.ar, which [uses Gamedig to query a list of servers](https://github.com/electricservers/electricservers.com.ar/blob/main/src/routes/%2Blayout.server.ts) to show in the frontend, throws a 500 error when deployed (successfully) to Vercel, but works perfectly normal when running it locally, through dev AND building/preview.

**Where can I begin trying to fix this issue? Is this even the right place to ask?**

Vercel logs point to gamedig:

```
2022-12-28T18:16:33.972Z	26eed3a2-844b-476c-ad87-cc122de3d410	ERROR	Error: Failed all 1 attempts
    at QueryRunner.run (/var/task/node_modules/.pnpm/gamedig@4.0.5/node_modules/gamedig/lib/QueryRunner.js:95:21)
    at async Gamedig.query (/var/task/node_modules/.pnpm/gamedig@4.0.5/node_modules/gamedig/lib/index.js:11:16)
    at async Gamedig.query (/var/task/node_modules/.pnpm/gamedig@4.0.5/node_modules/gamedig/lib/index.js:19:16)
    at async load (file:///var/task/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:27:5)
    at async load_server_data (file:///var/task/.svelte-kit/output/server/index.js:946:18)
    at async file:///var/task/.svelte-kit/output/server/index.js:1935:18
Attempt #1 - Port=27034 Retry=0:
Error: Cannot find module './lib/freeze'
Require stack:
- /var/task/node_modules/.pnpm/compressjs@1.0.3/node_modules/compressjs/main.js
- /var/task/node_modules/.pnpm/gamedig@4.0.5/node_modules/gamedig/protocols/valve.js
- /var/task/node_modules/.pnpm/gamedig@4.0.5/node_modules/gamedig/lib/ProtocolResolver.js
- /var/task/node_modules/.pnpm/gamedig@4.0.5/node_modules/gamedig/lib/QueryRunner.js
- /var/task/node_modules/.pnpm/gamedig@4.0.5/node_modules/gamedig/lib/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at req (/var/task/node_modules/.pnpm/amdefine@1.0.1/node_modules/amdefine/amdefine.js:144:31)
    at stringRequire (/var/task/node_modules/.pnpm/amdefine@1.0.1/node_modules/amdefine/amdefine.js:220:28)
    at amdRequire (/var/task/node_modules/.pnpm/amdefine@1.0.1/node_modules/amdefine/amdefine.js:113:24)
    at /var/task/node_modules/.pnpm/amdefine@1.0.1/node_modules/amdefine/amdefine.js:177:24
    at Array.map (<anonymous>)
    at runFactory (/var/task/node_modules/.pnpm/amdefine@1.0.1/node_modules/amdefine/amdefine.js:176:25)
    at define (/var/task/node_modules/.pnpm/amdefine@1.0.1/node_modules/amdefine/amdefine.js:277:13)
```

**Comment by SenkyDragon** [comment]
I don't have any experience with pnpm, but does that `node_modules/.pnpm/compressjs@1.0.3/node_modules/compressjs/lib/freeze.js` file actually exist on the server? It should, because it's part of compressjs.

**Comment by c43721** [comment]
You should try to reproduce in a fresh skit app with gamedig and see if that also fails to deploy to vercel

**Comment by xCausxn** [comment]
Vercel could be blocking those outbound connections.

The game server network could also be blocking the vercel IP.

**Comment by maxijabase** [comment]
Replaced gamedig with https://github.com/Fabricio-191/valve-server-query and now it's working as intended
https://github.com/maxijabase/gamedig-test/commit/2ec161f34a996ed4290efd92dd8dbd14c8866365

**Comment by mmorrisontx** [comment]
This definitely isn't a networking issue. I suspect there's something wrong with the way pnpm is installing the compressjs package. `Error: Cannot find module './lib/freeze'` makes it sound like the lib/freeze.js file is missing from compressjs, while that's definitely not the case: https://github.com/cscott/compressjs/blob/master/lib/freeze.js

**Comment by maxijabase** [comment]
I made some changes to the project by deleting all pnpm references, installing all packages through npm, and overriding the install command in Vercel to `npm install`
![image](https://user-images.githubusercontent.com/20617661/210014974-16d823ce-e20b-45e9-ba12-e062e7ddca4f.png)
Unfortunately the issue still persists:
```ts
[GET] /api/servers
18:58:02:66
2022-12-29T21:58:02.738Z	144bc8c4-0cb1-4772-aee4-00225bf16e0b	ERROR	Error: Failed all 1 attempts
    at QueryRunner.run (/var/task/node_modules/gamedig/lib/QueryRunner.js:95:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Gamedig.query (/var/task/node_modules/gamedig/lib/index.js:11:16)
    at async Gamedig.query (/var/task/node_modules/gamedig/lib/index.js:19:16)
    at async GET (file:///var/task/.svelte-kit/output/server/entries/endpoints/api/servers/_server.ts.js:4:16)
    at async render_endpoint (file:///var/task/.svelte-kit/output/server/index.js:280:22)
    at async resolve (file:///var/task/.svelte-kit/output/server/index.js:2248:22)
    at async respond (file:///var/task/.svelte-kit/output/server/index.js:2152:22)
    at async Server.default (file:///var/task/.svelte-kit/vercel-tmp/index.js:31:3)
Attempt #1 - Port=27034 Retry=0:
Error: Cannot find module './lib/freeze'
Require stack:
- /var/task/node_modules/compressjs/main.js
- /var/task/node_modules/gamedig/protocols/valve.js
- /var/task/node_modules/gamedig/lib/ProtocolResolver.js
- /var/task/node_modules/gamedig/lib/QueryRunner.js
- /var/task/node_modules/gamedig/lib/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at req (/var/task/node_modules/amdefine/amdefine.js:144:31)
    at stringRequire (/var/task/node_modules/amdefine/amdefine.js:220:28)
    at amdRequire (/var/task/node_modules/amdefine/amdefine.js:113:24)
    at /var/task/node_modules/amdefine/amdefine.js:177:24
    at Array.map (<anonymous>)
    at runFactory (/var/task/node_modules/amdefine/amdefine.js:176:25)
    at define (/var/task/node_modules/amdefine/amdefine.js:277:13)
```

**Comment by maxijabase** [comment]
[buildlog.log](https://github.com/gamedig/node-gamedig/files/10322262/buildlog.log)

**Comment by mmorrisontx** [comment]
So strange. Is there any way to see the file tree after the build happens? Does the /var/task/node_modules/compressjs/lib/freeze.js file actually exist? Seems like compressjs is getting pretty old these days (last published 7 years ago 👀), so maybe it's time for us to find a replacement anyways. Strange that it would only cause issues in this one spot though.

**Comment by mmorrisontx** [comment]
oh, I guess I didn't realize Vercel tries to build all the libs into a single package file. It's probably trying (and failing) to follow the require reference that compressjs uses in its main.js, which is a little atypical: https://github.com/cscott/compressjs/blob/master/main.js#L1

I'm actually surprised gamedig would work at all, since the games.txt file probably wouldn't be located in the right spot. Gamedig wasn't really written to be bundled.

**Comment by mmorrisontx** [comment]
https://github.com/vercel/next.js/discussions/32236?sort=new#discussioncomment-3029649 makes it sound like this is an unsolved problem, and vercel doesn't seem super enthusiastic about providing a solution.

**Comment by maxijabase** [comment]
I've been looking into ways of peeking into the file tree post-deployment but was unsuccessful. Is there anything I can do to provide better insights on this?

**Comment by shamoon** [comment]
Sorry to revive an old thread, Im just trying re-trace down this rabbit-hole but it seems we're hitting the same issue: https://github.com/benphelps/homepage/issues/1795

Adding the `outputFileTracingIncludes` doesnt seem to solve this unfortunately (unless Im doing it wrong) and upgrading nextjs to v13 isn't so trivial for us (and unclear if that fixes it...)

**Comment by CosminPerRam** [comment]
Hey, could someone check if the linked PR solves this problem?

**Comment by alexevladgabriel** [comment]
Seems to work now with NextJS deployed on Vercel: https://gamedig-test-coral.vercel.app/
