### ISSUE TITLE
feat: Add support for ARK: Survival Ascended

### ISSUE THREAD

**Issue by GuilhermeWerner** [gamedig/node-gamedig#395]
**What is this feature about?**
I would like to help add support to ARK: Survival Ascended.

**Additional context/references**
ARK: Survival Evolved is already implemented, however ARK: Survival Ascended does not use Valve's services (apparently), but rather Epic Online Services.

**I performed some tests on my server:**

IP: 189.90.255.6
Port: 7805
Query Port: 27060
SO: Windows Server 2022

![image](https://github.com/gamedig/node-gamedig/assets/26710260/30fa4330-c1dd-4c39-8043-78ad994dc08a)

**Using `arkse` protocol:**

```sh
node .\bin\gamedig.js --type arkse 189.90.255.6:27060 --debug
```

```sh
Q#0 Starting
Q#0 Protocol: valve
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  ipFamily: 0,
  port: 27060,
  protocol: 'valve',
  requestRules: false,
  type: 'arkse',
  host: '189.90.255.6',
  debug: true
}
Q#0 DNS Lookup: 189.90.255.6
Q#0 Raw IP Address: 189.90.255.6
Q#0 Requesting info ...
189.90.255.6:27060 UDP(65157)-->
Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (file:///C:/Projects/node-gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Error: Failed all 1 attempts
    at QueryRunner.run (file:///C:/Projects/node-gamedig/lib/QueryRunner.js:90:17)
    at async Gamedig.query (file:///C:/Projects/node-gamedig/lib/index.js:11:12)
Attempt #1 - Port=27060 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (file:///C:/Projects/node-gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

![image](https://github.com/gamedig/node-gamedig/assets/26710260/444cb62d-43db-4935-a8e2-1f3204085133)
![image](https://github.com/gamedig/node-gamedig/assets/26710260/9a79c870-1b36-4007-8b5b-ab4cc568071f)
![image](https://github.com/gamedig/node-gamedig/assets/26710260/4d65a524-2f40-49a2-9722-084aa426c3ec)

**Using `unreal` protocol:**

```sh
node .\bin\gamedig.js --type unreal 189.90.255.6:7805 --debug
```

```sh
Q#0 Starting
Q#0 Protocol: gamespy1
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  ipFamily: 0,
  port: 7806,
  protocol: 'gamespy1',
  requestRules: false,
  type: 'unreal',
  host: '189.90.255.6',
  debug: true
}
Q#0 DNS Lookup: 189.90.255.6
Q#0 Raw IP Address: 189.90.255.6
189.90.255.6:7806 UDP(51881)-->
Buffer length: 20 bytes
5c 73 74 61 74 75 73 5c 78 73 65 72 76 65 72 71 75 65 72 79
\  s  t  a  t  u  s  \  x  s  e  r  v  e  r  q  u  e  r  y

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (file:///C:/Projects/node-gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Q#1 Starting
Q#1 Protocol: gamespy1
Q#1 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  ipFamily: 0,
  port: 7805,
  protocol: 'gamespy1',
  requestRules: false,
  type: 'unreal',
  host: '189.90.255.6',
  debug: true
}
Q#1 DNS Lookup: 189.90.255.6
Q#1 Raw IP Address: 189.90.255.6
189.90.255.6:7805 UDP(51881)-->
Buffer length: 20 bytes
5c 73 74 61 74 75 73 5c 78 73 65 72 76 65 72 71 75 65 72 79
\  s  t  a  t  u  s  \  x  s  e  r  v  e  r  q  u  e  r  y

189.90.255.6:7805 <--UDP(51881)
Buffer length: 22 bytes
fc 81 01 82 05 23 4e ff 69 00 80 cf a9 30 d3 07 ae 4c 46 8b 79
               #  N     i              0           L  F     y
ea


Q#1 Registered RTT: 30ms
Q#1 Received part num=undefined queryId=undefined final=false
Q#1 No part number received (assigned #0)
Q#1 Received part #0 of ?
Q#1 UDP timeout detected
Q#1 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (file:///C:/Projects/node-gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Error: Failed all 2 attempts
    at QueryRunner.run (file:///C:/Projects/node-gamedig/lib/QueryRunner.js:90:17)
    at async Gamedig.query (file:///C:/Projects/node-gamedig/lib/index.js:11:12)
Attempt #1 - Port=7806 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (file:///C:/Projects/node-gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Attempt #2 - Port=7805 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (file:///C:/Projects/node-gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

![image](https://github.com/gamedig/node-gamedig/assets/26710260/4bb3c94e-cb00-4464-a3ad-39961ea8703c)
![image](https://github.com/gamedig/node-gamedig/assets/26710260/0a71d8c0-2dee-4d96-b9e1-453d4ed343a0)
![image](https://github.com/gamedig/node-gamedig/assets/26710260/7461e4b9-6325-46ed-9035-c256a728c349)

![image](https://github.com/gamedig/node-gamedig/assets/26710260/caa5e279-eeb7-4798-abae-0c8e8857994e)
![image](https://github.com/gamedig/node-gamedig/assets/26710260/8ac3439e-9c3f-4e2c-84ee-7680f7256753)

**Comment by CosminPerRam** [comment]
Thanks for being interested into making the library better.
Just as you stated, the newer game seems to use EOS, which I still haven't found [how to query](https://forums.unrealengine.com/t/eos-server-query-like-the-valve-server-query-protocol/1324417).
Seems a bit strange that it responds to unreal2.
We still have to sort out EOS stuff then I suppose the support could be easily be added.

**Comment by Default-01** [comment]
Looking forward to this!

**Comment by CosminPerRam** [comment]
I couldn't make anything of that Unreal2 response.
I see that [Studio Wildcard](www.studiowildcard.com) and [Grove Street Games](https://grovestreetgames.com/) are the developers, I've emailed them regarding this, I hope they'll responde.

**Comment by GuilhermeWerner** [comment]
> I couldn't make anything of that Unreal2 response. I see that [Studio Wildcard](www.studiowildcard.com) and [Grove Street Games](https://grovestreetgames.com/) are the developers, I've emailed them regarding this, I hope they'll responde.

Okay, let's see what they say.

As I commented in #396, these are the ARK: Survival Ascended credentials to connect to Epic services:
```cpp
struct SampleConstants
{   
    static constexpr char GameName[] = "ARK Survival Ascended";
    static constexpr char ProductId[] = "985dc4d67ff142588b6393c46b1dff84";
    static constexpr char ClientCredentialsId[] = "xyza7891qC5rMxf0e76B4lGe5qePQXNy";
    static constexpr char ClientCredentialsSecret[] = "14BiZqLRckVJ49d9fZ";
    static constexpr char SandboxId[] = "dae80c0d4e3b4d648498b48af609b8bb";
    static constexpr char DeploymentId[] = "ad9a8feffb3b4b2ca315546f038c3ae2";
    static constexpr char EncryptionKey[] = "e624fa4ad499d56822531fe94058cc44a3af014633b83aedfe14346d33c8c35e";
};
```

They are used to list servers, matchmaking, stats and the other features provided by EOS.

Another observation is that these credentials were extracted from the game's executable, using a disassembler.

My idea is that when we manage to obtain data from one or more servers using the SDK, create something like a dynamic library in C++ and call it from NodeJS in the case of this gamedig version, and through FFI for the Rust version.

I also searched to see if there were other ways to obtain this data, via an Epic web api or something like that, but so far without success.

I left the credentials and these observations here so that if anyone else wants to test, the more people help, the better. 😁

**Comment by GuilhermeWerner** [comment]
I found out one thing, the server listens on http port 8888.

I was looking through ASA ModKit and found a plugin:

![image](https://github.com/gamedig/node-gamedig/assets/26710260/624eb2c8-03b5-41e2-a0d1-12abfba060a5)

Inside the plugin folder there is the openapi specification:
```yml
openapi: 3.0.3
info:
  title: Nitrado Game Server Plugin
  version: 0.1.0
  description: |
    This describes the Game Query protocol used for Nitrado-hosted dedicated
    game servers.
  contact:
    name: Nitrado SteelShield
    email: steelshield@nitrado.net
  license:
    name: proprietary
security: []
servers:
- url: http://localhost:8888/v1
components:
  schemas:
    GameServerDetails:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          required:
            - name
            - game
            - addresses
            - password
            - playerCount
            - playerMax
            - version
          properties:
            uniqueId:
              type: string
              example: a1a2f151-43ba-4773-b0e8-df2144cc3997
              description: The unique ID of the server.
            game:
              type: string
              example: "MyGame"
            serverName:
              type: string
              example: server name
              description: The name of the server.
            ports:
              type: array
              description: The addresses this game server can be reached on.
              items:
                type: object
                required:
                  - port
                  - type
                  - address
                properties:
                  type:
                    type: string
                    enum:
                      - game
                      - query
                      - rcon
                  address:
                    type: string
                    format: ipv4
                    description: The IP address where the port is listening
                  port:
                    type: integer
                    format: uint16
                    default: 7777
            password:
              type: boolean
              description: Indicates if the server requires a password to join.
            playerMax:
              type: integer
              example: 20
              description: The maximum number of players that can join the server.
            playerCount:
              type: integer
              example: 3
              description: The current number of players on the server.
            playerReserved:
              type: integer
              description: Amount of player slots reserved.
            botCount:
              type: integer
              description: Amount of player slots used up by bots.
            ticksPerSecond:
              type: integer
              description: Returns the current tick count
            ready:
              type: boolean
              description: Returns the current ready status (server is fully started and accepts new connections)
            mods:
              type: array
              description: List of mods loaded on this game server.
              items:
                type: object
                example: {"id": "fe1e1374542c5570fdaace94fa0822c3027b7b21", "version": "1.2.3.4", "name": "Mod of God"}
                properties:
                  id:
                    description: Mod unique ID.
                    type: string
                  version:
                    description: Mod version.
                    type: string
                  name:
                    description: Mod name.
                    type: string
            mapName:
              type: string
              description: The current map running on the server.
              example: TheIsland
            version:
              type: string
              description: The version of the server.
              example: "1.2.3.4"
            platforms:
              type: array
              description: Defines the platforms which are supported by that game servers
              uniqueItems: true
              example:
                - xbox
                - playstation
              items:
                type: string
                enum:
                  - XBOX
                  - PLAYSTATION
                  - SWITCH
                  - MAC
                  - PC
                  - ANDROID
                  - IOS
            tags:
              type: array
              description: |
                Additional values assigned to the game server.
              items:
                type: string
                default: "secure"
  responses:
    GameServerQueryResponse:
      x-summary: Information about the dedicated game server.
      description: |
        This response contains detailed information in relation to this
        dedicated game server.
      content:
        application/vnd.nitrado.gameserver.query+json:
          schema:
            $ref: "#/components/schemas/GameServerDetails"
paths:
  /ready:
    get:
      operationId: checkReady
      summary: Check game server readiness
      description: |
        This endpoint indicates whether the server accepts player connections based on
        the status code.
      responses:
        '200':
          # TODO - is 204 No Content a better idea since we provide no content?
          # TODO - should we document any 2xx code being okay?
          description: |
            This response is returned only once the game server is fully started and accepts
            player connections.
        '503':
          # TODO - better error handling by providing more descriptive error codes?
          description: |
            This response is returned in any other remaining case, including errors and
            right before the server is about to shut down.
  /query:
    get:
      operationId: queryGameServerInfo
      summary: Query game server information
      description: |
        This endpoint returns information about the dedicated game server and its state.
        The information is kept up to date on the server side and the endpoint will need
        to be called again to collect the updated information.
      responses:
        '200':
          $ref: "#/components/responses/GameServerQueryResponse"
```

I tested it on my server on the same machine and it worked.

![image](https://github.com/gamedig/node-gamedig/assets/26710260/0233b448-3dff-49aa-bb77-d8487ac37c97)

But unfortunately the server only listens to the address 127.0.0.1.

![image](https://github.com/gamedig/node-gamedig/assets/26710260/7d585641-57a2-4974-8cdd-30ac6296c104)

**Comment by GuilhermeWerner** [comment]
In the nitrado plugin readme, it is said that it is possible to change the query port by adding this to the `Engine.ini` file, along with modifying the bind address to 0.0.0.0 to allow external connections.

```ini
[/Script/NitradoGameServerQuery.GameServerQuerySubsystem]
bEnableReadyEndpoint=True
bEnableQueryEndpoint=True
QueryPort=8888
bEnablePlugin=True

[HTTPServer.Listeners]
ListenerOverrides=(Port=8888,BindAddress="0.0.0.0")
```

However, I was only able to modify the bind address, changing the query port had no effect.

![image](https://github.com/gamedig/node-gamedig/assets/26710260/956eac91-202a-48ba-b48d-b4cad4c76059)

This way I was able to redirect the ports and perform the query externally.

Now we just have to test on public servers to see if this works and if it's the same port or another.

**Comment by CosminPerRam** [comment]
> Okay, let's see what they say.
Grove Street Games told that they take care strictly of the console ports and that I should contact WildCard, and they did not responded yet.

**Comment by CosminPerRam** [comment]
Solved by #402.

**Comment by Default-01** [comment]
@guilhermewerner Currently there is an issue with Asa not properly fetching data and returning an error code. Could you take a look and use some magic to find out on whats the issue?

Its about #762

**Comment by guilhermewerner** [comment]
> [@guilhermewerner](https://github.com/guilhermewerner) Currently there is an issue with Asa not properly fetching data and returning an error code. Could you take a look and use some magic to find out on whats the issue?
> 
> Its about [#762](https://github.com/gamedig/node-gamedig/issues/762)

Sorry for the delay, it seems to be some kind of permissions issue on Epic's end.

Here: https://github.com/gamedig/node-gamedig/issues/762#issuecomment-4185702199
