### ISSUE TITLE
bug: Left 4 Dead 2 Queries No Longer Working

### ISSUE THREAD

**Issue by Kr3m** [gamedig/node-gamedig#494]
**Describe the bug**
Left 4 Dead 2 queries no longer working.

**Steps To Reproduce**
gamedig --type left4dead2 server:port

**Expected behavior**
Results from the query.

**Screenshots or Data**
{"error":"Failed all 1 attempts"}

**Comment by CosminPerRam** [comment]
Hey, could you provide the server ip and port? I just queried some random servers and everything seems to be fine.
If you're hosting this server make sure all the needed ports are open.
Also please add the debug logs by passing `--debug` to the command.

**Comment by Kr3m** [comment]
Yeah, I just noticed that myself a while ago when I tested it on another server.  The server is at chi.kr3m.one and the ports are 27015-27018.  I have them open.  It was actually working fine until a few days ago, and then I don't know what happened.

**Comment by Kr3m** [comment]
`TypeError: type.substr is not a function
    at GameResolver.lookup (/usr/local/lib/node_modules/gamedig/lib/GameResolver.js:14:17)
    at QueryRunner.run (/usr/local/lib/node_modules/gamedig/lib/QueryRunner.js:32:31)
    at Gamedig.query (/usr/local/lib/node_modules/gamedig/lib/index.js:11:39)
    at Object.<anonymous> (/usr/local/lib/node_modules/gamedig/bin/gamedig.js:45:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)`

**Comment by Kr3m** [comment]
`Q#0 Starting
Q#0 Protocol: Valve
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  ipFamily: 0,
  port: 27015,
  protocol: 'valve',
  requestRules: false,
  type: 'left4dead2',
  host: 'chi.kr3m.one',
  debug: true
}
Q#0 DNS Lookup: chi.kr3m.one
Q#0 Standard Resolve: chi.kr3m.one
Q#0 Found address: 127.0.0.1
Q#0 Requesting info ...
127.0.0.1:27015 UDP(46795)-->
Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75 
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u  
65 72 79 00 
e  r  y     

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/usr/local/lib/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Error: Failed all 1 attempts
    at QueryRunner.run (/usr/local/lib/node_modules/gamedig/lib/QueryRunner.js:96:21)
Attempt #1 - Port=27015 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/usr/local/lib/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by podrivo** [comment]
Hello @Kr3m! Are you still having errors?

I've just tried querying the example you provided and it's working for me.
Make sure you're using the query port and not the game port. So in this example, `27018` and not `27015`.

```
gamedig --type left4dead2 chi.kr3m.one:27018 --pretty

{
  "name": "DayenTech.net L4D2 #4",
  "map": "fnaf1_survival_n6",
  "password": false,
  "raw": {
    "protocol": 17,
    "folder": "left4dead2",
    "game": "Left 4 Dead 2",
    "appId": 550,
    "numplayers": 0,
    "numbots": 0,
    "listentype": "d",
    "environment": "l",
    "secure": 1,
    "version": "2.2.3.0",
    "steamid": "90180058245841935",
    "tags": [
      "survival",
      "empty",
      "secure"
    ]
  },
  "maxplayers": 4,
  "players": [],
  "bots": [],
  "connect": "chi.kr3m.one:27018",
  "ping": 163
}
```

**Comment by podrivo** [comment]
Hello @Kr3m! Do you still need support about this?

**Comment by CosminPerRam** [comment]
Closing this as its most likely a networking issue, it works for me and @podrivo, maybe the server is too far away or your internet connection is not very good and it drops packages or is very slow (try increasing the `socketTimeout` option (default `2000` - which is 2 seconds)).
Feel free to reopen if this is still persistent.
