### ISSUE TITLE
Palworld Querying 8211 is not working but other server using 8212 and up is working

### ISSUE THREAD

**Issue by ohmcodes** [gamedig/node-gamedig#509]
line 1761
lib/games.js

why port is 8221? the default should be 8211 right? also when im querying 8211 it doesnt work as it is my port then i have another server using 8212 it does work

**Comment by joebywan** [comment]
Have the same, port listed as 8211 by default, but gamedig is querying 8221.  Typo?

`npx gamedig --type palworld 127.0.0.1 8211 --debug
Q#0 Starting
Q#0 Protocol: palworld
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxRetries: 1,
  stripColors: true,
  portCache: true,
  noBreadthOrder: false,
  ipFamily: 0,
  port: 8221,
  protocol: 'palworld',
  pretty: false,
  debug: true,
  givenPortOnly: false,
  requestRules: false,
  requestRulesRequired: false,
  requestPlayersRequired: false,
  checkOldIDs: false,
  type: 'palworld',
  host: '127.0.0.1'
}
Q#0 DNS Lookup: 127.0.0.1
Q#0 Raw IP Address: 127.0.0.1
Q#0 Requesting external access token ...
Q#0 Requesting deviceId access token ...
Q#0 POST: https://api.epicgames.dev/auth/v1/accounts/deviceid
Q#0 https://api.epicgames.dev/auth/v1/accounts/deviceid HTTP-->
Q#0 https://api.epicgames.dev/auth/v1/accounts/deviceid <--HTTP 200
Q#0 POST: https://api.epicgames.dev/auth/v1/oauth/token
Q#0 https://api.epicgames.dev/auth/v1/oauth/token HTTP-->
Q#0 https://api.epicgames.dev/auth/v1/oauth/token <--HTTP 200
Q#0 POST: https://api.epicgames.dev/matchmaking/v1/0a18471f93d448e2a1f60e47e03d3413/filter
Q#0 https://api.epicgames.dev/matchmaking/v1/0a18471f93d448e2a1f60e47e03d3413/filter HTTP-->
Q#0 https://api.epicgames.dev/matchmaking/v1/0a18471f93d448e2a1f60e47e03d3413/filter <--HTTP 200
Q#0 Query failed with error Error: Server not found
    at palworld.queryInfo (file:///usr/lib/node_modules/gamedig/protocols/epic.js:126:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async palworld.run (file:///usr/lib/node_modules/gamedig/protocols/epic.js:34:5)
    at async palworld.run (file:///usr/lib/node_modules/gamedig/protocols/palworld.js:15:5)
    at async palworld.runOnce (file:///usr/lib/node_modules/gamedig/protocols/core.js:80:5)
    at async palworld.runOnceSafe (file:///usr/lib/node_modules/gamedig/protocols/core.js:54:22)
    at async QueryRunner._attempt (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:118:12)
    at async QueryRunner.run (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:95:26)
    at async GameDig.query (file:///usr/lib/node_modules/gamedig/lib/gamedig.js:11:12)
Error: Failed all 1 attempts
    at QueryRunner.run (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:106:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GameDig.query (file:///usr/lib/node_modules/gamedig/lib/gamedig.js:11:12)
Attempt #1 - Port=8221 Retry=0:
Error: Server not found
    at palworld.queryInfo (file:///usr/lib/node_modules/gamedig/protocols/epic.js:126:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async palworld.run (file:///usr/lib/node_modules/gamedig/protocols/epic.js:34:5)
    at async palworld.run (file:///usr/lib/node_modules/gamedig/protocols/palworld.js:15:5)
    at async palworld.runOnce (file:///usr/lib/node_modules/gamedig/protocols/core.js:80:5)
    at async palworld.runOnceSafe (file:///usr/lib/node_modules/gamedig/protocols/core.js:54:22)
    at async QueryRunner._attempt (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:118:12)
    at async QueryRunner.run (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:95:26)
    at async GameDig.query (file:///usr/lib/node_modules/gamedig/lib/gamedig.js:11:12)
`

**Comment by CosminPerRam** [comment]
The default port being wrong is fixed by #516.
> another server using 8212 it does work

Is that the server's port? If yes, that's to be expected.

**Comment by ohmcodes** [comment]
i fixed mine by forwarding 8211 and 8212 for gameport and queryport+1 this is always doing by many servers sometimes gameport is 2 and another one for query port plus rcon port like on ASA or ASE you have to forward 4 ports

**Comment by Mululu** [comment]
Can you explain in more detail what you did?

**Comment by Mululu** [comment]
> i fixed mine by forwarding 8211 and 8212 for gameport and queryport+1 this is always doing by many servers sometimes gameport is 2 and another one for query port plus rcon port like on ASA or ASE you have to forward 4 ports

Can you explain in more detail what you did?

**Comment by ohmcodes** [comment]
> > i fixed mine by forwarding 8211 and 8212 for gameport and queryport+1 this is always doing by many servers sometimes gameport is 2 and another one for query port plus rcon port like on ASA or ASE you have to forward 4 ports
> 
> Can you explain in more detail what you did?

if you forward 8211 you need to port forward 8212 as well to make it work, 8211 steam uses it for the player to connect and 8212 is for sending data outside (querying) and its called query port :)

**Comment by Mululu** [comment]
I can't understand it or it doesn't work for me.

Game port: 8211
RCON Port: 25575
Steam query port 27015

Even if I release Gameport + 1, the server remains unfound for Gamedig.

**Comment by ohmcodes** [comment]
> I can't understand it or it doesn't work for me.
> 
> Game port: 8211 RCON Port: 25575 Steam query port 27015
> 
> Even if I release Gameport + 1, the server remains unfound for Gamedig.
> 
> ![image](https://private-user-images.githubusercontent.com/5918495/300269323-811f6980-a2b3-4906-abad-86ddfc498b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Nzk4MDIsIm5iZiI6MTcwNjQ3OTUwMiwicGF0aCI6Ii81OTE4NDk1LzMwMDI2OTMyMy04MTFmNjk4MC1hMmIzLTQ5MDYtYWJhZC04NmRkZmM0OThiMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMjIwNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlkYTkzYTgyYjU5ZjNiZWU5ZmU0NjZmZDMyYWEzZmFjYmVhY2NiNjBjZDlkOGE1NWU2YmEwNTMxZDkwNWY2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HwGjs_5jOBWiv7WXZY1DiMyKfhguaFemQCBRrPJhJ-s)

dont set the query port to 27015 forward 8212 if you are using 8211 if you want to use 27015 for query port you need to use 27014 on gameport
