### ISSUE TITLE
Evrima server not returning databug: something is not working

### ISSUE THREAD

**Issue by Bilalfr123** [gamedig/node-gamedig#521]
**Describe the bug**
Fetching the data for evrima server but it returning error `Failed all 2 attempts`
**Steps To Reproduce*
```
import { GameDig } from "gamedig";

async function test() {
	
	GameDig.query({
		type: "tie",
		// type: "theisle",
		// host: "104.206.80.154:14110",
		address: "104.206.80.154",
		port: "14100",
		// rawRules: true,
	})
		.then((state) => {
			console.log(state);
		})
		.catch((error) => {
			console.log(`Server is offline, error: ${error}`);
		});

}

test();
```
**Expected behavior**
Well, i am testing three the isle servers they work fine. But for evrima, its returning the error. I see in the docs its supported.

**Comment by CosminPerRam** [comment]
Hello, could you provide the servers you tested and failed? I see you've written an example code for theisle while having problems for envirma, right?
Also, it would be useful to add the debug logs via the `debug: true` option (or --debug in CLI).

**Comment by GuilhermeWerner** [comment]
With port 14100 it worked normally:
![image](https://github.com/gamedig/node-gamedig/assets/26710260/47643bcc-f76d-454b-af02-2a649c1c19e5)

**Comment by Bilalfr123** [comment]
The isle servers i tested and they work: `104.206.80.154:14010, 104.206.80.154:14210`
The evrima server i tested and dont work: `104.206.80.154:14100`
the logs
`Q#0 Starting
Q#0 Protocol: theisleevrima
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxRetries: 1,
  stripColors: true,
  portCache: true,
  noBreadthOrder: false,
  ipFamily: 0,
  port: 14110,
  protocol: 'theisleevrima',
  type: 'tie',
  address: '104.206.80.154',
  debug: true
}
Q#0 Requesting client access token ...
Q#0 POST: https://api.epicgames.dev/auth/v1/oauth/token
Q#0 https://api.epicgames.dev/auth/v1/oauth/token HTTP-->
(node:10036) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
Q#0 Query failed with error RequestError: Timeout awaiting 'request' for 2000ms
    at ClientRequest.<anonymous> (file:///C:/Users/My%20Pc/Desktop/djs/node_modules/got/dist/source/core/index.js:792:61)
    at Object.onceWrapper (node:events:627:26)
    at ClientRequest.emit (node:events:524:35)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (file:///C:/Users/My%20Pc/Desktop/djs/node_modules/got/dist/source/core/timed-out.js:42:25)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
Q#1 Starting
Q#1 Protocol: theisleevrima
Q#1 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxRetries: 1,
  stripColors: true,
  portCache: true,
  noBreadthOrder: false,
  ipFamily: 0,
  port: 14110,
  protocol: 'theisleevrima',
  type: 'tie',
  address: '104.206.80.154',
  debug: true
}
Q#1 Requesting client access token ...
Q#1 POST: https://api.epicgames.dev/auth/v1/oauth/token
Q#1 https://api.epicgames.dev/auth/v1/oauth/token HTTP-->
(node:10036) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
Q#1 Query failed with error RequestError: Timeout awaiting 'request' for 2000ms
    at ClientRequest.<anonymous> (file:///C:/Users/My%20Pc/Desktop/djs/node_modules/got/dist/source/core/index.js:792:61)
    at Object.onceWrapper (node:events:627:26)
    at ClientRequest.emit (node:events:524:35)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (file:///C:/Users/My%20Pc/Desktop/djs/node_modules/got/dist/source/core/timed-out.js:42:25)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
Server is offline, error: Error: Failed all 2 attempts`

**Comment by podrivo** [comment]
It worked for me on port `14100`.

```
gamedig --type tie 104.206.80.154:14100 --pretty

{
  "name": "New Beginnings Spiro",
  "map": "Isla_Spiro",
  "raw": {
    "deployment": "6db6bea492f94b1bbdfcdfe3e4f898dc",
    "id": "8c040f7845824ae68ee7314a1e9f5d8c",
    "bucket": "<None>:<None>:<None>",
    "settings": {
      "maxPublicPlayers": 115,
      "allowInvites": true,
      "shouldAdvertise": true,
      "allowReadById": true,
      "allowJoinViaPresence": true,
      "allowJoinInProgress": true,
      "allowConferenceRoom": false,
      "checkSanctions": false,
      "allowMigration": false,
      "rejoinAfterKick": "",
      "platforms": null
    },
    "totalPlayers": 0,
    "openPublicPlayers": 115,
    "publicPlayers": [],
    "started": true,
    "lastUpdated": "2024-01-29T16:55:26.388Z",
    "attributes": {
      "SERVERNAME_s": "New Beginnings Spiro",
      "PASSWORD_s": "Password",
      "QUEUE_ENABLED_b": false,
      "SERVER_VERSION_s": "0.11.59.04",
      "PASSWORD_ENABLED_b": false,
      "QUEUE_PORT_s": "14102",
      "ADDRESS_s": "104.206.80.154",
      "__EOS_BLISTENING_b": true,
      "MAP_NAME_s": "Isla_Spiro",
      "ADDRESSBOUND_s": "0.0.0.0:14100",
      "IP_s": "104.206.80.154",
      "__EOS_BUSESPRESENCE_b": false,
      "DISCORD_s": "https://discord.gg/KPtBfwD7qw",
      "OFFICIAL_b": false
    },
    "owner": "Client_xyza7891gk5PRo3J7G9puCJGFJjmEguW",
    "ownerPlatformId": null
  },
  "maxplayers": 115,
  "numplayers": 0,
  "players": [],
  "bots": [],
  "queryPort": 14100,
  "connect": "104.206.80.154:14100",
  "ping": 0
}
```

**Comment by GuilhermeWerner** [comment]
It looks like you are using the wrong port, 14110 not 14100.

**Comment by Bilalfr123** [comment]
> With port 14100 it worked normally: ![image](https://private-user-images.githubusercontent.com/26710260/300539976-47643bcc-f76d-454b-af02-2a649c1c19e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDc2MTksIm5iZiI6MTcwNjU0NzMxOSwicGF0aCI6Ii8yNjcxMDI2MC8zMDA1Mzk5NzYtNDc2NDNiY2MtZjc2ZC00NTRiLWFmMDItMmE2NDljMWMxOWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE2NTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljY2NhYTA0ZjkxMzY5NzUzMmJmYzRjYjc5NGQxN2MxNzJhMDJkOWRhZjVmODllMzQxZGYyNDc3YWJlYTNhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ub7OrdIsOAXclQIsHixDqQUEpYi783Xel66VE1CQ0Rg)

Apparently, it doesnt seem to work for me. Niether the command line 
![Uploading Capture.PNG…]()

**Comment by CosminPerRam** [comment]
So you've solved this? Good to close?

**Comment by podrivo** [comment]
Glad it's working! (:

**Comment by Bilalfr123** [comment]
there's actually some problem , it worked once now its giving the same error again.

**Comment by podrivo** [comment]
Just tried multiple times and it worked on all attempts.
I've used this command, with port `14100`:

```
gamedig --type tie 104.206.80.154:14100
```

**Comment by Bilalfr123** [comment]
`
Q#0 Starting
Q#0 Protocol: theisleevrima
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxRetries: 1,
  stripColors: true,
  portCache: true,
  noBreadthOrder: false,
  ipFamily: 0,
  port: 14100,
  protocol: 'theisleevrima',
  type: 'tie',
  address: '104.206.80.154',
  debug: true
}
Q#0 Requesting client access token ...
Q#0 POST: https://api.epicgames.dev/auth/v1/oauth/token
Q#0 https://api.epicgames.dev/auth/v1/oauth/token HTTP-->
(node:16124) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
Q#0 Query failed with error RequestError: Timeout awaiting 'request' for 2000ms
    at ClientRequest.<anonymous> (file:///C:/Users/My%20Pc/Desktop/djs/node_modules/got/dist/source/core/index.js:792:61)
    at Object.onceWrapper (node:events:627:26)
    at ClientRequest.emit (node:events:524:35)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (file:///C:/Users/My%20Pc/Desktop/djs/node_modules/got/dist/source/core/timed-out.js:42:25)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
Q#1 Starting
Q#1 Protocol: theisleevrima
Q#1 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxRetries: 1,
  stripColors: true,
  portCache: true,
  noBreadthOrder: false,
  ipFamily: 0,
  port: 14100,
  protocol: 'theisleevrima',
  type: 'tie',
  address: '104.206.80.154',
  debug: true
}
Q#1 Requesting client access token ...
Q#1 POST: https://api.epicgames.dev/auth/v1/oauth/token
Q#1 https://api.epicgames.dev/auth/v1/oauth/token HTTP-->
(node:16124) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
Q#1 Query failed with error RequestError: Timeout awaiting 'request' for 2000ms
    at ClientRequest.<anonymous> (file:///C:/Users/My%20Pc/Desktop/djs/node_modules/got/dist/source/core/index.js:792:61)
    at Object.onceWrapper (node:events:627:26)
    at ClientRequest.emit (node:events:524:35)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (file:///C:/Users/My%20Pc/Desktop/djs/node_modules/got/dist/source/core/timed-out.js:42:25)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
Server is offline, error: Error: Failed all 2 attempts
`
Could it be an IP problem?
