### ISSUE TITLE
bug: Trackmania Nations Forever Query not possible

### ISSUE THREAD

**Issue by Hornochs** [gamedig/node-gamedig#634]
**Describe the bug**
Querying Trackmania Nations Forever is not possible and runs into an error

**Steps To Reproduce**

- Setup Trackmania Nations Forever Server and enable XML-RPC on all ports (Easy TM Deployment by https://github.com/lduriez/tmserver-docker)
- Query Server with following code:
```
const { GameDig } = require('gamedig'); 

GameDig.query({
    type: 'trackmaniaforever',
    host: '10.13.37.7',
    port: '5000',
    login: 'User',
    password: 'User',
    debug: true
}).then((state) => {
    console.log(state);
}).catch((error) => {
    console.log(`Server is offline, error: ${error}`);
});
```

**Expected behavior**
Successfull Query

**Screenshots or Data**
Following is the Debug Log:

```
Q#0 DNS Lookup: 10.13.37.7
Q#0 Raw IP Address: 10.13.37.7
Q#0 Registered RTT: 87ms
Q#0 Query failed with error Error: XML-RPC fault: Method 'GetCurrentMapInfo' not defined
    at createFault (/home/stephanschaffner/gamedig/node_modules/xmlrpc/lib/deserializer.js:83:21)
    at Deserializer.onDone (/home/stephanschaffner/gamedig/node_modules/xmlrpc/lib/deserializer.js:89:21)
    at SAXStream.emit (node:events:517:28)
    at SAXStream._parser.onend (/home/stephanschaffner/gamedig/node_modules/sax/lib/sax.js:190:10)
    at emit (/home/stephanschaffner/gamedig/node_modules/sax/lib/sax.js:624:35)
    at end (/home/stephanschaffner/gamedig/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.end (/home/stephanschaffner/gamedig/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/home/stephanschaffner/gamedig/node_modules/sax/lib/sax.js:248:18)
    at StringStream.onend (/home/stephanschaffner/gamedig/node_modules/string-to-stream/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:631:28)
```

**Additional context**
I'm in the finding if its a GameDig Bug, or a GameServer Bug

**Comment by CosminPerRam** [comment]
Seems like its a GameDig issue.
The query fails here: 
https://github.com/gamedig/node-gamedig/blob/30ed54dfcdbc5fb1d7fb5f7e1d23c61ec1e640c3/protocols/nadeo.js#L23
And if you comment this, then here:
https://github.com/gamedig/node-gamedig/blob/30ed54dfcdbc5fb1d7fb5f7e1d23c61ec1e640c3/protocols/nadeo.js#L43
If I comment both blocks, the query succeeds.

Maybe the API changed or the server hasnt loaded a map yet, still investigating.

**Comment by Hornochs** [comment]
Or maybe the current handler is for the current games? Trackmania Nations (Forever) is quite old. Maybe the API was changed with the later Nadeo Games?

**Comment by CosminPerRam** [comment]
> Or maybe the current handler is for the current games? Trackmania Nations (Forever) is quite old. Maybe the API was changed with the later Nadeo Games?

No, as far as I know, the protocol hasn't changed in a good while.

Some docs regarding available methods: [ListMethods.txt](https://github.com/user-attachments/files/17042130/ListMethods.txt) (renamed to .txt from .html cause Github wouldn't let me attach it otherwise).

**Comment by Hornochs** [comment]
#669 Is adding the correct Method to query Mapnames. But there is more testing necessary to chech different API Versions. 

While https://wiki.trackmania.io/en/dedicated-server/XML-RPC/Methods states Methods, its only for the newest Trackmania Versions.

Maybe it needs seperate protocols or different calles by gamename
